/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sledrv66mndhhofy2conifb5za.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nqbfilr6tjcqlcvtdk62tmztam",
    "aws_cognito_identity_pool_id": "us-east-1:67efee47-09ad-43f1-a647-de9cec0d86b9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Bo6NEBnVP",
    "aws_user_pools_web_client_id": "2b5bjljo1pkb79ihas949s2vdo",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_mobile_analytics_app_id": "4f655f8a7c53413c823a629616156e63",
    "aws_mobile_analytics_app_region": "us-east-1"
};


module.exports = {default: awsmobile};
